return {
    Tier1 = {
        { Name = "Cobalt", ID = 17 },
        { Name = "Silver", ID = 18 },
        { Name = "Limestone", ID = 34 },
        { Name = "Tin", ID = 35 },
        { Name = "Sulfur", ID = 36 },
        { Name = "Coal", ID = 1 },
        { Name = "Iron", ID = 2 },
        { Name = "Copper", ID = 3 },
        { Name = "Gold", ID = 6 },
        { Name = "Jadeshard", ID = 37 },
        { Name = "Magnetite", ID = 39 },
        { Name = "Quartz", ID = 5 },
        { Name = "Amberresin", ID = 38 },
        { Name = "Prismsand", ID = 40 },
    },
    Tier2 = {
        { Name = "Tungsten", ID = 15 },
        { Name = "Titanium", ID = 16 },
        { Name = "Opal", ID = 41 },
        { Name = "Ruby", ID = 10 },
        { Name = "Platinum", ID = 12 },
        { Name = "Rubonit", ID = 19 },
        { Name = "Glowstone", ID = 21 },
        { Name = "Saphire", ID = 42 },
        { Name = "Cursedbones", ID = 44 },
        { Name = "Bloodgarnet", ID = 45 },
        { Name = "Emerald", ID = 8 },
        { Name = "Whiteking", ID = 46 },
        { Name = "Shadowglass", ID = 43 },
        { Name = "Stormsteel", ID = 47 },
    },
    Tier3 = {
        { Name = "Uranium", ID = 13 },
        { Name = "Diamond", ID = 14 },
        { Name = "Herostone", ID = 48 },
        { Name = "Suncrystal", ID = 49 },
        { Name = "Voidcrystal", ID = 50 },
        { Name = "Frostium", ID = 9 },
        { Name = "Soulstone", ID = 20 },
        { Name = "Aetherite", ID = 7 },
        { Name = "Pyroium", ID = 11 },
        { Name = "Lightnium", ID = 22 },
        { Name = "Merium", ID = 23 },
    },
    Tier4 = {
        { Name = "Dirt", ID = 51 },
        { Name = "Bismuthinite", ID = 52 },
        { Name = "Cassiterite", ID = 53 },
        { Name = "Molybdenite", ID = 54 },
        { Name = "Glowfungium", ID = 63 },
        { Name = "Mithium", ID = 55 },
        { Name = "Mycelite", ID = 61 },
        { Name = "Astralite", ID = 56 },
        { Name = "Aetherglass", ID = 62 },
        { Name = "Echoquartz", ID = 64 },
        { Name = "Voidium", ID = 57 },
        { Name = "Solarite", ID = 58 },
        { Name = "Nebulium", ID = 59 },
        { Name = "Gravitanium", ID = 60 },
        { Name = "Araxium", ID = 65 },
    },
    Tier5 = {
        { Name = "Purequartz", ID = 71 },
        { Name = "BloodResin", ID = 72 },
        { Name = "Ancienticeium", ID = 73 },        
        { Name = "Ferrum", ID = 74 },
        { Name = "Etimmuium", ID = 75 },
        { Name = "Hamarrium", ID = 76 },
        { Name = "Bloodhorn", ID = 77 },           
        { Name = "Redone", ID = 78 },
        { Name = "Oldroot", ID = 80 },
        { Name = "Dreadstone", ID = 81 },
        { Name = "Entitycore", ID = 82 },
        { Name = "Solinvictusium", ID = 83 },
        { Name = "Powershard", ID = 84 },
        { Name = "Speedshard", ID = 85 },
        { Name = "Luckshard", ID = 86 },
    },
    SummerEvent = {
        { Name = "Palm", ID = 70 },
        { Name = "Coralbloom", ID = 68 },
        { Name = "Lavaspine", ID = 69 },
        { Name = "Frostcoral", ID = 67 },
        { Name = "Aquashell", ID = 66 },
    },
    VolcanoEvent = {
        { Name = "Magmajaw", ID = 88 },
        { Name = "Flarecore", ID = 89 },
        { Name = "Emberstone", ID = 90 },
        { Name = "Lavaspike", ID = 79 },
        { Name = "Basalt", ID = 91 },
        { Name = "Pyrespike", ID = 92 },  
    },
}
